:hammer: fix blackWhiteList feature
ca-gip/kubi pull request #40
Opened 2024-10-24 08:55 UTC by pape07

Sans ce changement les nouveaux projects ne sont jamais créés si au moins un projet est présent dans le blacklist et que la fonctionnalité whitelist n'est pas activée

2024-10-24 17:05 UTC, evrardjp requested changes
While it works/could work, I am not seeing everything that can prove it: No tests.

Please add a unit test, covering all 3 cases mentioned here (possibly more with fuzzing).

2024-10-24 17:05 UTC, evrardjp commented on internal/services/provisionner.go
> +		default:
This is a nit.

2024-10-28 15:27 UTC, pape07 commented on internal/services/provisionner.go
> +		//delete CR project of blacklisted projects
j'ai update

2024-11-15 12:53 UTC, evrardjp approved these changes
I didn't test the change. But at first sight, it looks okay.

I will approve, but I would like to see a follow up commit for two reasons:
1) The tests are hard to read or lie a bit.
2) Plenty of nits.

2024-11-15 12:53 UTC, evrardjp commented on internal/services/provisionner.go
> +func GenerateProjects(context []*types.Project, blackWhiteList *types.BlackWhitelist) ([]*types.Project, []*types.Project, []*types.Project) {
we create new project slices, so it would have been better to not point to []* but let's keep this for now

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +	t.Run("whitelist_enabled_and_projects_in_blacklist", func(t *testing.T) {
nit: could rename as: "keep_only_projects_in_whitelist_with_deletion_of_blacklist"

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +		assert.ElementsMatch(t,got,expected, "the project is in ognored projects")
nit: typo

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +	t.Run("whitelist_enabled_and_project_is_on_both_lists", func(t *testing.T) {
nit: i think the name of the test is not obvious. It does not explain the test, it explains the input of the test. You can change that on a follow-up commit.

Example of test name. "blacklist_even_when_on_whitelist"

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +		expected := []*types.Project{
does this make sense? If whitelist is enabled and nothing is in whitelist, shouldn't there be nothing in the expected Project list? You don't seem to test it.

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +
nit: missing a whitelist_enabled and no projects in blacklist/whitelist for example. can you do it in a follow up commit?

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
>  			"whitelist": "native-divelopment",
nit: if that name is not a typo, we should rather make it explicit ;)

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +		assert.ElementsMatch(t,got,expected,"the project is in ignored projects")
this is deleted, not ignored.

2024-11-15 12:53 UTC, evrardjp commented on internal/services/blackwhitelist_test.go
> +		{
the tests are hard to read. could you use a triple slice in expected, containing created, deleted, and ignored projects, so we can loop over tests with very explicit cases?

2024-11-15 17:43 UTC, evrardjp approved these changes
not tested but lgtm

2024-11-15 17:44 UTC, merged